version: "3.8"

services:
    database:
        image: mariadb:10.6.17
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shopware
            MYSQL_USER: shopware
            MYSQL_PASSWORD: shopware
        ports:
            - 3306:3306
    shopware:
        image: shyim/shopware:6.4.20-php8.2
        environment:
            # openssl rand -hex 32
            APP_SECRET: e2c99b53e834d8220a57b02c53d3a210ac3ce42ea16981f0c5a0e37dfa368083
            # openssl rand -hex 32
            INSTANCE_ID: ccc9af909f47581c307beaa26e2d245d771779b75ede59b51ddb5f989eaf86b4
            APP_URL: http://localhost:8080
            BLUE_GREEN_DEPLOYMENT: 0
            # host is required for container in addition to URL
            DATABASE_HOST: database
            DATABASE_URL: mysql://shopware:shopware@database:3306/shopware
            INSTALL_LOCALE: de-DE
            INSTALL_CURRENCY: EUR
            TZ: Europe/Berlin
        ports:
            - 8080:8080
        volumes:
            - ./custom/plugins:/var/www/html/custom/plugins