name: Build With Github

on:
  push:
    # build and bundle for every branch push
    branches: ["*"]
    # create github release when commit was marked via "git tag"
    tags: ["v*"]

jobs:
  Bundle-ZIP-Extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create shopware extension bundle
        uses: actions/upload-artifact@v4
        with:
          name: extension-folder
          path: |
            ./custom/plugins/*
  Create-Github-Draft-Release:
    needs: [Bundle-ZIP-Extension]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Download extension as ZIP
        uses: dawidd6/action-download-artifact@v6
        with:
          skip_unpack: true
          name: extension-folder
      - name: create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            *.zip
